import "server-only";

import { generateTextForTask } from "./ai-provider";
import { hasAIProviderForTask } from "./ai-models";
import type { SourceBias, BiasRating } from "./bias";
import { BIAS_LABELS, biasToPosition } from "./bias";
import type { FeedItem } from "./rss";

// ============================================================================
// AI BIAS DIGEST — Claude-powered feed bias analysis
//
// Takes the current feed's source distribution + article headlines and
// generates a 1-2 sentence editorial bias insight. Falls back to a
// statistical summary when no API key is available.
// ============================================================================

export interface BiasDigest {
  /** AI-generated or computed bias insight (1-2 sentences) */
  insight: string;
  /** Whether this was generated by AI or computed locally */
  source: "ai" | "computed";
  /** Average factuality rating label */
  avgFactuality: string;
  /** Weighted bias center-of-mass: -3 (far left) to +3 (far right) */
  tilt: number;
  /** Human-readable tilt label */
  tiltLabel: string;
}

const FACTUALITY_SCORES: Record<string, number> = {
  "very-high": 5,
  "high": 4,
  "mostly-factual": 3,
  "mixed": 2,
  "low": 1,
  "very-low": 0,
};

const FACTUALITY_LABELS_REVERSE: Record<number, string> = {
  5: "Very High",
  4: "High",
  3: "Mostly Factual",
  2: "Mixed",
  1: "Low",
  0: "Very Low",
};

function computeTilt(sources: SourceBias[]): number {
  if (sources.length === 0) return 0;
  const sum = sources.reduce((acc, s) => acc + biasToPosition(s.bias) - 3, 0);
  return parseFloat((sum / sources.length).toFixed(2));
}

function tiltToLabel(tilt: number): string {
  if (tilt <= -1.5) return "Strong left tilt";
  if (tilt <= -0.5) return "Leans left";
  if (tilt <= -0.15) return "Slight left lean";
  if (tilt <= 0.15) return "Balanced";
  if (tilt <= 0.5) return "Slight right lean";
  if (tilt <= 1.5) return "Leans right";
  return "Strong right tilt";
}

function computeAvgFactuality(sources: SourceBias[]): string {
  if (sources.length === 0) return "Unknown";
  const total = sources.reduce(
    (acc, s) => acc + (FACTUALITY_SCORES[s.factuality] ?? 3),
    0,
  );
  const avg = Math.round(total / sources.length);
  return FACTUALITY_LABELS_REVERSE[avg] || "High";
}

/**
 * Compute a statistical bias insight without AI.
 * Used as fallback when ANTHROPIC_API_KEY is not set.
 */
function computeLocalDigest(sources: SourceBias[]): BiasDigest {
  const tilt = computeTilt(sources);
  const tiltLabel = tiltToLabel(tilt);
  const avgFactuality = computeAvgFactuality(sources);

  const leftCount = sources.filter(
    (s) => s.bias === "far-left" || s.bias === "left" || s.bias === "lean-left",
  ).length;
  const rightCount = sources.filter(
    (s) => s.bias === "far-right" || s.bias === "right" || s.bias === "lean-right",
  ).length;
  const centerCount = sources.filter((s) => s.bias === "center").length;
  const total = sources.length;

  const leftPct = Math.round((leftCount / total) * 100);
  const rightPct = Math.round((rightCount / total) * 100);
  const centerPct = Math.round((centerCount / total) * 100);

  // Build a meaningful statistical insight
  let insight: string;
  if (Math.abs(tilt) <= 0.15) {
    insight = `Feed coverage is balanced across ${total} sources (${centerPct}% center). Average factuality: ${avgFactuality.toLowerCase()}.`;
  } else if (tilt < 0) {
    insight = `Feed tilts left — ${leftPct}% of ${total} sources lean left vs ${rightPct}% right. Average factuality: ${avgFactuality.toLowerCase()}.`;
  } else {
    insight = `Feed tilts right — ${rightPct}% of ${total} sources lean right vs ${leftPct}% left. Average factuality: ${avgFactuality.toLowerCase()}.`;
  }

  return { insight, source: "computed", avgFactuality, tilt, tiltLabel };
}

/**
 * Generate an AI-powered bias digest using Claude Haiku.
 * Analyzes source distribution + recent headlines to produce an editorial bias note.
 */
export async function generateBiasDigest(
  sources: SourceBias[],
  headlines?: string[],
): Promise<BiasDigest> {
  const tilt = computeTilt(sources);
  const tiltLabel = tiltToLabel(tilt);
  const avgFactuality = computeAvgFactuality(sources);

  // If no API key, return statistical fallback
  if (!hasAIProviderForTask("biasDigest")) {
    return computeLocalDigest(sources);
  }

  // Build a compact distribution summary for the prompt
  const dist: Record<BiasRating, string[]> = {
    "far-left": [], "left": [], "lean-left": [],
    "center": [],
    "lean-right": [], "right": [], "far-right": [],
  };
  for (const s of sources) {
    dist[s.bias].push(s.name);
  }

  const distSummary = (Object.entries(dist) as [BiasRating, string[]][])
    .filter(([, names]) => names.length > 0)
    .map(([bias, names]) => `${BIAS_LABELS[bias]} (${names.length}): ${names.join(", ")}`)
    .join("\n");

  const headlineBlock = headlines && headlines.length > 0
    ? `\nTop headlines:\n${headlines.slice(0, 15).map((h) => `- ${h}`).join("\n")}`
    : "";

  try {
    const result = await generateTextForTask({
      task: "biasDigest",
      maxTokens: 150,
      temperature: 0.3,
      timeoutMs: 8_000,
      system:
        "You are a media analyst. Given a news feed's source distribution and headlines, write exactly ONE sentence (max 30 words) analyzing the editorial bias landscape. Be specific about blind spots or overrepresentation. No preamble.",
      user: `Source distribution:\n${distSummary}\n\nTilt: ${tiltLabel} (${tilt.toFixed(2)})\nAvg factuality: ${avgFactuality}${headlineBlock}\n\nOne-sentence bias analysis:`,
    });

    const insight = result.text.trim();

    if (insight && insight.length > 10 && insight.length < 300) {
      return { insight, source: "ai", avgFactuality, tilt, tiltLabel };
    }
  } catch (err) {
    console.warn("[bias-digest] AI generation failed, using computed:", err instanceof Error ? err.message : err);
  }

  return computeLocalDigest(sources);
}
