// Build-time version stamp for the worker.
//
// The worker deploys via manual `railway up` (no GitHub integration), so
// RAILWAY_GIT_COMMIT_SHA is usually unset. We resolve the SHA at build time
// from whatever is available, in priority order, and write a generated module
// the worker imports. This is the only reliable way to know which commit is
// actually running in production.
//
// Resolution order:
//   1. WORKER_GIT_SHA            (explicit override, e.g. set by a deploy script)
//   2. RAILWAY_GIT_COMMIT_SHA    (set automatically only for GitHub-linked services)
//   3. `git rev-parse HEAD`      (works when .git is present in the build context)
//   4. "unknown"

import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, "..", "src", "worker", "version.generated.ts");

function resolveSha() {
  if (process.env.WORKER_GIT_SHA) return process.env.WORKER_GIT_SHA.trim();
  if (process.env.RAILWAY_GIT_COMMIT_SHA) return process.env.RAILWAY_GIT_COMMIT_SHA.trim();
  try {
    return execSync("git rev-parse HEAD", { stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return "unknown";
  }
}

const sha = resolveSha();
const builtAt = new Date().toISOString();

const contents = `// AUTO-GENERATED by scripts/stamp-version.mjs at build time. Do not edit.
export const WORKER_VERSION = {
  sha: ${JSON.stringify(sha)},
  shaShort: ${JSON.stringify(sha === "unknown" ? "unknown" : sha.slice(0, 9))},
  builtAt: ${JSON.stringify(builtAt)},
} as const;
`;

writeFileSync(outPath, contents, "utf8");
console.log(`[stamp-version] wrote ${outPath} sha=${sha === "unknown" ? "unknown" : sha.slice(0, 9)} builtAt=${builtAt}`);
