import { BRAND_DOMAIN, BRAND_NAME, withBrand } from "@/lib/brand";

export const metadata = {
  title: withBrand("Terms & Risk"),
  description: `Terms of use and risk disclosure for ${BRAND_NAME}: experimental software, onchain permanence, unaudited contracts, no financial advice.`,
};

/*
  DRAFT — NOT LEGAL ADVICE.
  Written in plain language by the operators. Not yet reviewed by a solicitor.
  This page replaces the former sitewide "High-Risk Beta" toast; the risk
  wording that used to live in that toast is section II below.
  TODO: solicitor review alongside /privacy.
*/

interface Section {
  id: string;
  title: string;
  body: React.ReactNode;
}

const LAST_UPDATED = "6 September 2026";

const SECTIONS: Section[] = [
  {
    id: "what-this-is",
    title: "I. What this is",
    body: (
      <>
        <p>
          {BRAND_NAME} is an experimental news, discussion and public-record
          platform. Parts of it run on public blockchains (Base, Ethereum),
          parts are generated by AI systems, and parts are operated by
          autonomous software agents. By using the site you accept these terms.
        </p>
        <p>
          It is operated by a very small team. Features change, break and are
          removed without notice.
        </p>
      </>
    ),
  },
  {
    id: "risk",
    title: "II. Risk disclosure",
    body: (
      <>
        <p>
          <strong>This platform is experimental. Use it at your own risk.</strong>
        </p>
        <ul>
          <li>
            <strong>Smart contracts.</strong> Our contracts have been reviewed
            internally and by automated tooling, but have <strong>not</strong>{" "}
            been audited by an independent security firm. They may contain
            bugs that lose funds. Most are upgradeable by the operator.
          </li>
          <li>
            <strong>Tips and onchain payments.</strong> ETH you send through
            the site goes either directly to a wallet address shown to you, or
            into a tipping contract. Tips to sources that have not verified
            ownership are held in escrow with no expiry and may never be
            claimed. Transactions on a blockchain cannot be reversed.
          </li>
          <li>
            <strong>Markets and agent trading.</strong> Prediction markets,
            signals, the <code>/markets</code> terminal and any autonomous
            trading shown on the site are experimental software acting on
            experimental signals. Nothing on this site is investment, trading
            or financial advice. Past performance shown is not indicative of
            future results. Do not trade on anything you read here.
          </li>
          <li>
            <strong>AI-generated content.</strong> Editorials, summaries,
            market-impact analysis and moral commentary are produced by AI
            models and may be wrong, out of date or biased. They are opinion,
            not reporting, and are labelled as such.
          </li>
          <li>
            <strong>Availability.</strong> No uptime guarantee. Data may be
            lost. Keep your own copies of anything you care about.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "ledger",
    title: "III. The Claim Ledger",
    body: (
      <>
        <p>
          The Claim Ledger records what public figures said, with a link to the
          primary source, and where possible compares it with published
          records. Every verdict is the Ledger&rsquo;s assessment on the linked
          record, not a statement of fact about a person. Verdicts are
          proposed by software and published only after human review.
        </p>
        <p>
          If you are the subject of a claim or verdict and believe it is
          inaccurate, use the right-of-reply and correction route at{" "}
          <a href="/ledger/dispute">/ledger/dispute</a>. Disputed items are
          marked as under review while checked.
        </p>
      </>
    ),
  },
  {
    id: "onchain",
    title: "IV. Onchain permanence",
    body: (
      <>
        <p>
          Comments, ratings, votes and tips written to a blockchain are public
          and permanent. We cannot edit or delete them for you. Do not post
          anything onchain you may later want removed. See{" "}
          <a href="/privacy">Privacy</a> for what we hold off-chain.
        </p>
      </>
    ),
  },
  {
    id: "conduct",
    title: "V. Your conduct",
    body: (
      <>
        <ul>
          <li>You are responsible for your wallet, keys and account.</li>
          <li>
            Do not post unlawful, defamatory or infringing material. We may
            hide off-chain content that breaks this rule; onchain content we
            can only stop displaying.
          </li>
          <li>Do not attempt to attack, overload or exploit the service or its contracts.</li>
        </ul>
      </>
    ),
  },
  {
    id: "liability",
    title: "VI. Liability and law",
    body: (
      <>
        <p>
          The service is provided &ldquo;as is&rdquo; without warranty of any
          kind. To the fullest extent permitted by law, the operators are not
          liable for any loss arising from your use of the site, its
          contracts, its content or its agents. Nothing in these terms limits
          liability that cannot be limited by law.
        </p>
        <p>
          These terms are governed by the laws of England and Wales. Contact:{" "}
          <a href="mailto:accounts@pooter.world">accounts@pooter.world</a>.
        </p>
      </>
    ),
  },
];

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-6">
      {/* Masthead */}
      <div className="mb-10 border-b-2 border-[var(--rule)] pb-4">
        <h1 className="font-masthead text-4xl text-[var(--ink)] sm:text-5xl">
          Terms &amp; Risk
        </h1>
        <p className="mt-2 font-body-serif text-sm italic text-[var(--ink-light)]">
          What you agree to by using {BRAND_NAME}, and what can go wrong.
          Written plainly, because you should not need a lawyer to read it.
        </p>
        <div className="mt-3 font-mono text-[8px] uppercase tracking-[0.25em] text-[var(--ink-faint)]">
          Last updated {LAST_UPDATED}
        </div>
      </div>

      {SECTIONS.map((section) => (
        <section key={section.id} id={section.id} className="mb-10 scroll-mt-16">
          <div className="mb-4 border-b-2 border-[var(--rule)] pb-2">
            <h2 className="font-headline text-xl text-[var(--ink)]">
              {section.title}
            </h2>
          </div>
          <div className="font-body-serif text-sm leading-relaxed text-[var(--ink-light)] [&_a]:text-[var(--accent-red)] [&_a]:underline [&_a]:underline-offset-2 [&_code]:font-mono [&_code]:text-[11px] [&_code]:text-[var(--ink)] [&_li]:mb-2 [&_p]:mb-3 [&_strong]:text-[var(--ink)] [&_ul]:list-disc [&_ul]:pl-5">
            {section.body}
          </div>
        </section>
      ))}

      <footer className="mt-12 border-t-2 border-[var(--rule)] pt-4 pb-8 text-center">
        <div className="mb-1 h-px bg-[var(--rule)]" />
        <div className="mb-3 h-[2px] bg-[var(--rule)]" />
        <p className="font-mono text-[7px] uppercase tracking-[0.3em] text-[var(--ink-faint)]">
          {BRAND_DOMAIN} &bull; experimental &bull; unaudited contracts &bull;
          not financial advice
        </p>
      </footer>
    </div>
  );
}
