import { NextRequest, NextResponse } from "next/server";
import { computeEntityHash } from "@/lib/entity";
import { getArchivedEditorial } from "@/lib/editorial-archive";
import { BRAND_NAME, SITE_URL } from "@/lib/brand";

// ============================================================================
// /api/edition/[tokenId] — OpenSea-standard ERC-721 metadata
//
// Computes the daily edition hash from tokenId, looks up the editorial archive,
// and returns structured JSON metadata for marketplaces.
// ============================================================================

const EPOCH = 1741651200; // March 11 2025 00:00 UTC (edition #1)
const SECONDS_PER_DAY = 86400;

interface RouteParams {
  params: Promise<{ tokenId: string }>;
}

export async function GET(request: NextRequest, { params }: RouteParams) {
  const { tokenId: tokenIdStr } = await params;
  const tokenId = parseInt(tokenIdStr, 10);

  if (!Number.isFinite(tokenId) || tokenId < 1) {
    return NextResponse.json({ error: "Invalid tokenId" }, { status: 400 });
  }

  // Compute the date for this edition
  const editionTimestamp = EPOCH + (tokenId - 1) * SECONDS_PER_DAY;
  const editionDate = new Date(editionTimestamp * 1000);
  const dateStr = editionDate.toLocaleDateString("en-GB", {
    weekday: "short",
    day: "numeric",
    month: "short",
    year: "numeric",
  });

  // Compute the daily edition hash for this date
  const year = editionDate.getUTCFullYear();
  const month = String(editionDate.getUTCMonth() + 1).padStart(2, "0");
  const day = String(editionDate.getUTCDate()).padStart(2, "0");
  const dailyId = `pooter-daily-${year}-${month}-${day}`;
  const hash = computeEntityHash(dailyId);

  // Look up the editorial archive
  const editorial = await getArchivedEditorial(hash).catch(() => null);

  const name = editorial
    ? `${BRAND_NAME} — Edition #${tokenId}: ${editorial.dailyTitle || editorial.primary.title}`
    : `${BRAND_NAME} — Edition #${tokenId}`;

  const description = editorial
    ? editorial.subheadline
    : `Daily edition #${tokenId} of ${BRAND_NAME} (${dateStr}).`;

  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || SITE_URL;

  const attributes: Array<{ trait_type: string; value: string | number }> = [
    { trait_type: "Edition", value: tokenId },
    { trait_type: "Date", value: dateStr },
  ];

  if (editorial) {
    if (editorial.dailyTitle) {
      attributes.push({ trait_type: "Daily Title", value: editorial.dailyTitle });
    }
    if (editorial.generatedBy) {
      attributes.push({ trait_type: "Generated By", value: editorial.generatedBy });
    }
    if (editorial.primary.category) {
      attributes.push({ trait_type: "Category", value: editorial.primary.category });
    }
    if (editorial.tags?.length) {
      for (const tag of editorial.tags.slice(0, 5)) {
        attributes.push({ trait_type: "Tag", value: tag });
      }
    }
    if (editorial.contentHash) {
      attributes.push({ trait_type: "Content Hash", value: editorial.contentHash });
    }
    if (editorial.editedBy) {
      attributes.push({ trait_type: "Edited By", value: editorial.editedBy });
    }
    if (editorial.editorialBody?.length) {
      // First paragraph as preview (metadata limit ~10KB)
      attributes.push({
        trait_type: "Editorial Preview",
        value: editorial.editorialBody[0].slice(0, 500),
      });
    }
  }

  // Use DALL-E illustration as primary image if available, newspaper SVG as fallback
  const hasIllustration = editorial?.hasIllustration || !!editorial?.illustrationBase64;
  const image = hasIllustration
    ? `${baseUrl}/api/edition/${tokenId}/illustration`
    : `${baseUrl}/api/edition/${tokenId}/image`;

  const metadata = {
    name,
    description,
    external_url: `${baseUrl}/article/${hash}`,
    image,
    // Keep the SVG newspaper as animation_url so OpenSea shows both
    ...(hasIllustration ? { animation_url: `${baseUrl}/api/edition/${tokenId}/image` } : {}),
    attributes,
  };

  return NextResponse.json(metadata, {
    headers: {
      "Cache-Control": "public, max-age=86400, s-maxage=86400",
    },
  });
}
