import { NextRequest, NextResponse } from "next/server";
import { BRAND_NAME, SITE_URL } from "@/lib/brand";
import { getEditionContext } from "@/lib/server/edition-context";

// ============================================================================
// /api/edition/[tokenId] — OpenSea-standard ERC-721 metadata
//
// Computes the daily edition hash from tokenId, looks up the editorial archive,
// and returns structured JSON metadata for marketplaces.
// ============================================================================

interface RouteParams {
  params: Promise<{ tokenId: string }>;
}

export async function GET(request: NextRequest, { params }: RouteParams) {
  const { tokenId: tokenIdStr } = await params;
  const tokenId = parseInt(tokenIdStr, 10);

  if (!Number.isFinite(tokenId) || tokenId < 1) {
    return NextResponse.json({ error: "Invalid tokenId" }, { status: 400 });
  }

  const {
    editorial,
    editorialHash,
    dateStr,
    officialTitle,
    officialContentHash,
    auctionExists,
    communityTitle,
    communityContentHash,
  } = await getEditionContext(tokenId);

  const isCommunityEdition = auctionExists;
  const displayTitle = isCommunityEdition
    ? communityTitle ?? `COMMUNITY EDITION #${tokenId}`
    : officialTitle ?? `Edition #${tokenId}`;

  const name = isCommunityEdition
    ? `${BRAND_NAME} — Community Edition #${tokenId}: ${displayTitle}`
    : `${BRAND_NAME} — Edition #${tokenId}: ${displayTitle}`;

  const description = isCommunityEdition
    ? editorial
      ? `Community-created historical edition for ${BRAND_NAME} dated ${dateStr}. The title and content hash are user-supplied auction metadata, not an official ${BRAND_NAME} editorial record. Reference article: ${officialTitle ?? editorial.primary.title}.`
      : `Community-created historical edition for ${BRAND_NAME} dated ${dateStr}. The title and content hash are user-supplied auction metadata, not an official ${BRAND_NAME} editorial record.`
    : editorial
      ? editorial.subheadline
      : `Daily edition #${tokenId} of ${BRAND_NAME} (${dateStr}).`;

  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || SITE_URL;

  const attributes: Array<{ trait_type: string; value: string | number }> = [
    { trait_type: "Edition", value: tokenId },
    { trait_type: "Date", value: dateStr },
    {
      trait_type: "Edition Type",
      value: isCommunityEdition ? "Community Auction Edition" : "Editorial Edition",
    },
  ];

  if (isCommunityEdition) {
    attributes.push({
      trait_type: "Metadata Source",
      value: "User-generated auction submission",
    });
    if (communityTitle) {
      attributes.push({ trait_type: "Community Title", value: communityTitle });
    }
    if (communityContentHash) {
      attributes.push({
        trait_type: "Community Content Hash",
        value: communityContentHash,
      });
    }
    if (officialTitle) {
      attributes.push({
        trait_type: "Reference Article",
        value: officialTitle,
      });
    }
    if (officialContentHash) {
      attributes.push({
        trait_type: "Reference Article Hash",
        value: officialContentHash,
      });
    }
  } else if (editorial) {
    if (editorial.dailyTitle) {
      attributes.push({ trait_type: "Daily Title", value: editorial.dailyTitle });
    }
    if (editorial.generatedBy) {
      attributes.push({ trait_type: "Generated By", value: editorial.generatedBy });
    }
    if (editorial.primary.category) {
      attributes.push({ trait_type: "Category", value: editorial.primary.category });
    }
    if (editorial.tags?.length) {
      for (const tag of editorial.tags.slice(0, 5)) {
        attributes.push({ trait_type: "Tag", value: tag });
      }
    }
    if (editorial.contentHash) {
      attributes.push({ trait_type: "Content Hash", value: editorial.contentHash });
    }
    if (editorial.editedBy) {
      attributes.push({ trait_type: "Edited By", value: editorial.editedBy });
    }
    if (editorial.editorialBody?.length) {
      // First paragraph as preview (metadata limit ~10KB)
      attributes.push({
        trait_type: "Editorial Preview",
        value: editorial.editorialBody[0].slice(0, 500),
      });
    }
  }

  // Use DALL-E illustration as primary image if available, newspaper SVG as fallback
  const hasIllustration = editorial?.hasIllustration || !!editorial?.illustrationBase64;
  const image = isCommunityEdition
    ? `${baseUrl}/api/edition/${tokenId}/image`
    : hasIllustration
      ? `${baseUrl}/api/edition/${tokenId}/illustration`
      : `${baseUrl}/api/edition/${tokenId}/image`;

  const metadata = {
    name,
    description,
    external_url: editorial
      ? `${baseUrl}/article/${editorialHash}`
      : `${baseUrl}/appendix`,
    image,
    // Keep the SVG newspaper as animation_url so OpenSea shows both
    ...(!isCommunityEdition && hasIllustration
      ? { animation_url: `${baseUrl}/api/edition/${tokenId}/image` }
      : {}),
    attributes,
  };

  return NextResponse.json(metadata, {
    headers: {
      "Cache-Control": "public, max-age=86400, s-maxage=86400",
    },
  });
}
