import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display, Libre_Baskerville, UnifrakturCook } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers/WagmiProvider";
import { Header } from "@/components/layout/Header";
import { MarqueeBanner } from "@/components/layout/MarqueeBanner";
import { ExtensionBanner } from "@/components/layout/ExtensionBanner";
import { IntroSplash } from "@/components/layout/IntroSplash";
import { BRAND_NAME, SITE_URL, withBrand } from "@/lib/brand";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  style: ["normal", "italic"],
});

const baskerville = Libre_Baskerville({
  variable: "--font-baskerville",
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
});

const fraktur = UnifrakturCook({
  variable: "--font-fraktur",
  subsets: ["latin"],
  weight: "700",
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: withBrand("Permissionless News & Onchain Discussion"),
  description:
    "Rate, discuss, and tip news content directly onchain. Censorship-resistant conversations powered by Base.",
  icons: {
    icon: "https://morality.s3.eu-west-2.amazonaws.com/brand/glyph.png",
  },
  openGraph: {
    type: "website",
    siteName: BRAND_NAME,
    locale: "en_US",
    title: withBrand("Permissionless News & Onchain Discussion"),
    description:
      "Rate, discuss, and tip news content directly onchain. Censorship-resistant conversations powered by Base.",
    // OG image is auto-generated by opengraph-image.tsx in this directory
  },
  twitter: {
    card: "summary_large_image",
    title: BRAND_NAME,
    description:
      "Permissionless news feed. Rate, discuss, and tip articles onchain via Base L2.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} ${baskerville.variable} ${fraktur.variable} min-h-screen bg-[var(--paper)] font-sans text-[var(--ink)] antialiased`}
      >
        <Providers>
          <IntroSplash />
          <MarqueeBanner />
          <ExtensionBanner />
          <Header />
          <main className="mx-auto max-w-7xl px-4 py-2">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
