import { fetchAllFeeds } from "@/lib/rss";
import { computeEntityHash } from "@/lib/entity";
import {
  findRelatedArticles,
  generateEditorial,
  formatDateline,
  estimateReadingTime,
} from "@/lib/article";
import { ArticleTemplate } from "@/components/article/ArticleTemplate";
import { notFound } from "next/navigation";

export const revalidate = 300; // 5 min

interface ArticlePageProps {
  params: Promise<{ hash: string }>;
}

export default async function ArticlePage({ params }: ArticlePageProps) {
  const { hash } = await params;
  const allItems = await fetchAllFeeds();

  // Find the article matching this hash
  const primary = allItems.find(
    (item) => computeEntityHash(item.link) === hash
  );

  if (!primary) {
    notFound();
  }

  // Find related articles from other sources
  const related = findRelatedArticles(primary, allItems, 5);

  // Generate editorial content
  const article = await generateEditorial(primary, related);

  // Compute metadata
  const dateline = formatDateline(primary.pubDate);
  const readTime = estimateReadingTime([
    ...article.editorialBody,
    article.wireSummary || "",
  ]);

  return (
    <ArticleTemplate
      article={article}
      dateline={dateline}
      readTime={readTime}
      entityHash={hash}
    />
  );
}

// Generate metadata for SEO
export async function generateMetadata({ params }: ArticlePageProps) {
  const { hash } = await params;
  const allItems = await fetchAllFeeds();
  const item = allItems.find(
    (item) => computeEntityHash(item.link) === hash
  );

  if (!item) {
    return { title: "Article Not Found" };
  }

  const description = item.description?.slice(0, 160) || "";
  const sourceInfo = item.bias
    ? `${item.source} (${item.bias.bias}) — ${item.category}`
    : `${item.source} — ${item.category}`;

  return {
    title: `${item.title} — pooter world`,
    description,
    openGraph: {
      title: item.title,
      description: `${sourceInfo}. ${description}`,
      type: "article",
      siteName: "pooter world",
      locale: "en_US",
      // OG image is auto-generated by opengraph-image.tsx in this directory
    },
    twitter: {
      card: "summary_large_image",
      title: item.title,
      description,
      // Twitter image is auto-picked up from opengraph-image.tsx
    },
  };
}
