// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.24;

/**
 * @title Groth16Verifier
 * @notice PLACEHOLDER — This file will be auto-generated by snarkjs from the
 *         password_recover.circom circuit. Run `circuits/password-recovery/build.sh`
 *         to produce the real verifier.
 *
 *         This placeholder exposes the correct interface so ZKRecovery.sol compiles
 *         and tests can mock it. The real verifier replaces this file entirely.
 *
 * @dev The verifier checks a Groth16 proof over BN254 (alt_bn128) with 4 public inputs:
 *      [0] commitment  — Poseidon(password, salt)
 *      [1] newAddress  — recovery target address (as uint256)
 *      [2] chainId     — EVM chain ID (8453 for Base)
 *      [3] nonce       — anti-replay counter from ZKRecovery contract
 */
contract Groth16Verifier {

    /**
     * @notice Verify a Groth16 proof.
     * @param _pA       Proof element A (2 uint256s)
     * @param _pB       Proof element B (2x2 uint256s)
     * @param _pC       Proof element C (2 uint256s)
     * @param _pubSignals Public inputs [commitment, newAddress, chainId, nonce]
     * @return True if the proof is valid
     */
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[4] calldata _pubSignals
    ) external view returns (bool) {
        // PLACEHOLDER: always returns true.
        // The real verifier generated by snarkjs performs elliptic curve
        // pairing checks on the BN254 curve using the EIP-196/197 precompiles.
        //
        // DO NOT DEPLOY THIS PLACEHOLDER TO MAINNET.
        //
        // To generate the real verifier:
        //   cd circuits/password-recovery
        //   ./build.sh
        //
        // This will overwrite this file with the production verifier.

        // Suppress unused variable warnings
        _pA; _pB; _pC; _pubSignals;
        return true;
    }
}
